// Mirrors the display_name of each rule in crates/core/src/classification.rs.
// Duplicated here (rather than an extra round trip per category id) so the
// dashboard/cleanup/developer pages can render a label immediately; keep in
// sync with the Rust knowledge base when adding a new rule there.
export const CATEGORY_LABELS: Record<string, string> = {
  "npm-cache-nested": "Package Manager Build Cache",
  "node-modules": "node_modules",
  "cargo-target-debug": "Cargo Build Output (debug)",
  "cargo-target-release": "Cargo Build Output (release)",
  "cargo-registry-cache": "Cargo Registry Cache",
  "npm-cache": "npm Cache",
  "pnpm-store": "pnpm Store",
  "yarn-cache": "Yarn Cache",
  "pip-cache": "pip Cache",
  "python-venv": "Python Virtual Environment",
  "gradle-cache": "Gradle Cache",
  "maven-repo": "Maven Local Repository",
  "jetbrains-cache": "JetBrains IDE Cache",
  "vscode-cache": "VS Code Extension Cache",
  "docker-data": "Docker Data",
  "git-internals": "Git Repository Data",
  "build-output-dist": "Build Output",
  "android-build": "Android Build Artifacts",
  "xcode-derived-data": "Xcode Derived Data",
  "xcode-archives": "Xcode Archives",
  "xcode-simulators": "Xcode Simulators",
  "xcode-device-support": "Xcode Device Support",
  "spm-cache": "Swift Package Manager Cache",
  "homebrew-cache": "Homebrew Cache",
  "cocoapods": "CocoaPods",
  "chrome-cache": "Chrome Cache",
  "firefox-cache": "Firefox Cache",
  "edge-cache": "Edge Cache",
  "windows-temp": "Windows Temporary Files",
  "windows-old": "Previous Windows Installation",
  "windows-update-cache": "Windows Update Cache",
  "delivery-optimization": "Delivery Optimization Files",
  "thumbnail-cache": "Thumbnail Cache",
  "directx-shader-cache": "DirectX Shader Cache",
  "recycle-bin": "Recycle Bin",
  "system-volume-information": "System Volume Information",
  "pagefile": "Virtual Memory Paging File",
  "hibernation-file": "Hibernation File",
  "downloads": "Downloads",
};
